### ISSUE TITLE
Installation command is wrong

### ISSUE THREAD

**Issue by arash28134** [aidan-clyens/TerrainGenerator#2]
About the installation process, "git clone git@github.com:aidan-clyens/TerrainGenerator.git" is wrong and it gives the "fatal: Could not read from remote repository." error. I believe it should be "git clone https://github.com/aidan-clyens/TerrainGenerator"
The full error message is:

```
Cloning into 'TerrainGenerator'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by aidan-clyens** [comment]
Do you have an SSH key associated with your account? Either way, good point the HTTP address is probably better. Thanks :)
